name: Lint
on: 
  push:
    paths:
      - 'src/**'
      - 'mod.ts'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'mod.ts'
      - 'tests/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
      - name: Run lint script
        run: deno lint src/** --unstable
