name: Test
on:
  pull_request:
    types: labeled
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'run-tests'
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
      - name: Run test script
        run: deno test --allow-net --allow-env ./test
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
